<h2>Sine up using this form</h2>

<?php
    // formタグを作ってsignupコントローラのregisterAction()にsubmitする
    echo $this->tag->form("signup/register");
?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textfield("name"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>