<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" >
</head>

<body>
<div class="container">
<?php
echo '<h1>User List<h1>';

echo PHP_EOL; // 改行
echo PHP_EOL;

// リンクを作成する
echo $this->tag->linkTo(
    "signup",               // コントローラ名(SingupController->indexAction())
    "sign Up Here!"         // リンクテキスト
);

if ( $users->count() > 0 ){
?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light" >
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
            </tr>
        <?php }?>
        </tbody>
    </table>
<?php
}
?>
</div>
</body>
</html>